version: '3.1'

services:
  gateway:
    image: songminkyu/fc-nestjs-gateway
    env_file:
      - ./apps/gateway/prod.env
    ports:
      - '3000:3000'

  user:
    image: songminkyu/fc-nestjs-user
    env_file:
      - ./apps/user/prod.env

  product:
    image: songminkyu/fc-nestjs-product
    env_file:
      - ./apps/product/prod.env

  order:
    image: songminkyu/fc-nestjs-order
    env_file:
      - ./apps/order/prod.env

  payment_command:
    image: songminkyu/fc-nestjs-payment-command
    env_file:
      - ./apps/payment-command/prod.env

  payment_query:
    image: songminkyu/fc-nestjs-payment-query
    env_file:
      - ./apps/payment-query/prod.env

  notification:
    image: songminkyu/fc-nestjs-notification
    env_file:
      - ./apps/notification/prod.env